id: QmcNQUmcumusKLuVBkiqUYa6wmeUsi8ByG9DNovdx8851h
description: ""
tags: []
source: libraries/database_handler
trigger:
    type: https
    method: DELETE
    paths:
        - /delete
domains:
    - database
execution:
    timeout: 2s
    memory: 10MB
    call: delete
