id: QmW5nEbynXSNTDdi8gKjDLntjBSgPcVR3wbmfadYngyULJ
description: ""
tags:
    - smartops:confirm_http
source: libraries/database_handler
trigger:
    type: https
    method: GET
    paths:
        - /get
domains:
    - database
execution:
    timeout: 2s
    memory: 10MB
    call: get
