id: QmXYBzQonnQtPPnG41yn8d419yi74PbDtb3iBYvpjeGzLi
description: ""
tags: []
source: libraries/database_handler
trigger:
    type: https
    method: GET
    paths:
        - /list
domains:
    - database
execution:
    timeout: 2s
    memory: 10MB
    call: list
