id: QmfM1TybPwEZMCJ66dFD2tyfDsafXj6no4UCWfQfpQJH9k
description: ""
tags:
    - smartops:confirm_http
source: libraries/database_handler
trigger:
    type: https
    method: PUT
    paths:
        - /set
domains:
    - database
execution:
    timeout: 2s
    memory: 10MB
    call: set
